# Generated by Django 5.1.2 on 2025-01-25 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productid', models.IntegerField()),
                ('Productname', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('Userid', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Firstname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productid', models.IntegerField()),
                ('Productname', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('Userid', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Logintable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=100)),
                ('Image', models.FileField(upload_to='')),
                ('Quantity', models.IntegerField()),
                ('Unitprice', models.IntegerField()),
                ('Brand', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='signuptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Loginid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appMM.logintable')),
            ],
        ),
    ]
